exercism/purescript

- .travis.yml
- bin/test.sh
Pull request for https://github.com/exercism/xpurescript/issues/23
> Added support for Travis cache (issue #23)

- .gitignore
- bin/test-one.sh
- bin/test.sh
Split test script into two parts:
- Running all exercises (the one we had before, used by Travis)
- Running a single exercise (saves time when testing a single exercise)
Also added some colors to the build log, a bit easier to spot specific exercises this way.
Example build: https://travis-ci.org/icyrockcom/xpurescript/builds/214856188
Let me know what you guys think.
> Support for running tests for a single exercise, colors

- config.json
- exercises/largest-series-product/bower.json
- exercises/largest-series-product/examples/src/LargestSeriesProduct.purs
- exercises/largest-series-product/src/LargestSeriesProduct.purs
- exercises/largest-series-product/test/Main.purs
> Added Largest Series Product exercise

- exercises/accumulate/test/Main.purs
A user was copying ```fromFoldable []``` from the test into his solution. ```Nil``` should be preferred I would think.
> Use Nil for empty list in test.

- config/exercise_readme.go.tmpl
- exercises/accumulate/README.md
- exercises/acronym/README.md
- exercises/all-your-base/README.md
- exercises/allergies/README.md
- exercises/atbash-cipher/README.md
- exercises/binary-search/README.md
- exercises/bob/README.md
- exercises/bracket-push/README.md
- exercises/crypto-square/README.md
- exercises/diamond/README.md
- exercises/difference-of-squares/README.md
- exercises/etl/README.md
- exercises/hamming/README.md
- exercises/hello-world/README.md
- exercises/isogram/README.md
- exercises/largest-series-product/README.md
- exercises/leap/README.md
- exercises/meetup/README.md
- exercises/pangram/README.md
- exercises/pascals-triangle/README.md
- exercises/raindrops/README.md
- exercises/scrabble-score/README.md
- exercises/triangle/README.md
- exercises/word-count/README.md
We are working towards making exercises stand-alone. That is to say: no more generating READMEs on the fly.
This will give maintainers more control over each individual exercise README, and it will also make some of the backend logic for delivering exercises simpler.
The README template uses the Go text/template package, and the default templates generate the same READMEs as we have been generating on the fly.  See the documentation in [regenerating exercise readmes][regenerate-docs] for details.
The READMEs can be generated at any time using a new 'generate' command in configlet. This command has not yet landed in master or been released, but can be built from source in the generate-readmes branch on [configlet][].
[configlet]: https://github.com/exercism/configlet
[regenerate-docs]: …
> Generate static exercise README templates

- bin/update-bower.sh
- exercises/accumulate/bower.json
- exercises/acronym/bower.json
- exercises/all-your-base/bower.json
- exercises/allergies/bower.json
- exercises/atbash-cipher/bower.json
- exercises/binary-search/bower.json
- exercises/bob/bower.json
- exercises/bracket-push/bower.json
- exercises/crypto-square/bower.json
- exercises/diamond/bower.json
- exercises/difference-of-squares/bower.json
- exercises/etl/bower.json
- exercises/hamming/bower.json
- exercises/hello-world/bower.json
- exercises/isogram/bower.json
- exercises/largest-series-product/bower.json
- exercises/leap/bower.json
- exercises/meetup/bower.json
- exercises/pangram/bower.json
- exercises/pascals-triangle/bower.json
- exercises/raindrops/bower.json
- exercises/scrabble-score/bower.json
- exercises/triangle/bower.json
- exercises/word-count/bower.json
Continuation of https://github.com/exercism/purescript/pull/71.
Fixes this:
* Fix each of the exercises (it should be only copying the bower.json, but need to confirm)
* Add a script to copy the common bower.json to all exercises to help with the development
Remaining:
* Add dependency checker to the build which would confirm that all exercises are using the same versions as the common bower.json
* Update documentation for contributing to mention the additional restrictions
@lpil please check it out if you have a moment.
> Add update-bower.sh and update bower.json of all exercises

- .travis.yml
- README.md
- bin/check-bower.sh
- bin/test-separate.sh
Continuation of https://github.com/exercism/purescript/pull/72
* Add dependency checker to the build which would confirm that all exercises are using the same versions as the common bower.json
* Update documentation for contributing to mention the additional restrictions
* Adds test-separate.sh that can be used to compile and test all exercises separately, instead of merging them like test.sh used in Travis build does. Had it built for previous testing, so figured I can include it. Might be useful down the road...
This completes things mentioned in https://github.com/exercism/purescript/pull/71.
@lpil please check if all good when you get a chance.
> Add bower checker, update travis to use it and add separate testing script

- config.json
- exercises/rna-transcription/README.md
- exercises/rna-transcription/bower.json
- exercises/rna-transcription/examples/src/RNATranscription.purs
- exercises/rna-transcription/src/RNATranscription.purs
- exercises/rna-transcription/test/Main.purs
Mostly followed the current exercises, in particular this PR #44. I see that some of the `config.json` keys have changed since that pull request so this will probably need some changes there.
> Add RNA Transcription exercise

- docs/INSTALLATION.md
Fixes a broken link in INSTALLING.md - on [the install page](http://exercism.io/languages/purescript/installation) the link currently ends up in a 404.
> fix broken link in INSTALLING.md

- etc/bower.json
- exercises/accumulate/bower.json
- exercises/acronym/bower.json
- exercises/all-your-base/bower.json
- exercises/allergies/bower.json
- exercises/atbash-cipher/bower.json
- exercises/binary-search/bower.json
- exercises/bob/bower.json
- exercises/bracket-push/bower.json
- exercises/collatz-conjecture/bower.json
- exercises/crypto-square/bower.json
- exercises/diamond/bower.json
- exercises/difference-of-squares/bower.json
- exercises/etl/bower.json
- exercises/hamming/bower.json
- exercises/hello-world/bower.json
- exercises/isogram/bower.json
- exercises/largest-series-product/bower.json
- exercises/leap/bower.json
- exercises/meetup/bower.json
- exercises/pangram/bower.json
- exercises/pascals-triangle/bower.json
- exercises/phone-number/bower.json
- exercises/raindrops/bower.json
- exercises/rna-transcription/bower.json
- exercises/scrabble-score/bower.json
- exercises/sum-of-multiples/bower.json
- exercises/triangle/bower.json
- exercises/word-count/bower.json
There has been some confusion caused by people following the given directions to install purescript, which installs version 0.13.2.  The confusion is caused when they try to build an exercise, and the build fails.
This is because `purescript` version 0.13.x requires `purescript-typelevel-prelude` version `v5.0.0` to work.
This PR bumps the version of `purescript-test-unit` to `v15.0.0`, which transitively updates the version of `purescript-typelevel-prelude` as well.
Note that this should still work with purescript v12.2.2 and up (see https://github.com/purescript/purescript-typelevel-prelude/releases/tag/v5.0.0)
> support purescript 0.13.x

- exercises/concept/booleans/.meta/config.json
- exercises/practice/accumulate/.meta/config.json
- exercises/practice/acronym/.meta/config.json
- exercises/practice/all-your-base/.meta/config.json
- exercises/practice/allergies/.meta/config.json
- exercises/practice/atbash-cipher/.meta/config.json
- exercises/practice/binary-search/.meta/config.json
- exercises/practice/bob/.meta/config.json
- exercises/practice/collatz-conjecture/.meta/config.json
- exercises/practice/crypto-square/.meta/config.json
- exercises/practice/diamond/.meta/config.json
- exercises/practice/difference-of-squares/.meta/config.json
- exercises/practice/etl/.meta/config.json
- exercises/practice/hamming/.meta/config.json
- exercises/practice/hello-world/.meta/config.json
- exercises/practice/isogram/.meta/config.json
- exercises/practice/largest-series-product/.meta/config.json
- exercises/practice/leap/.meta/config.json
- exercises/practice/meetup/.meta/config.json
- exercises/practice/pangram/.meta/config.json
- exercises/practice/pascals-triangle/.meta/config.json
- exercises/practice/phone-number/.meta/config.json
- exercises/practice/raindrops/.meta/config.json
- exercises/practice/rna-transcription/.meta/config.json
- exercises/practice/scrabble-score/.meta/config.json
- exercises/practice/sum-of-multiples/.meta/config.json
- exercises/practice/triangle/.meta/config.json
- exercises/practice/word-count/.meta/config.json
Each Concept and Practice Exercise will have to define a _blurb_, which is a short description of the exercise.
The blurb will be displayed on a track's exercises page and on exercise tooltips. For example:
Blurbs must be limited to 350 chars and will be truncated in some views.
For Practice Exercises that are based on an exercise defined in the problem-specification repo, the blurb must match the contents of the problem-specifications exercises, which is defined in its `metadata.yml` file. In this PR, we'll do an initial syncing of the blurb. The new [configlet](https://github.com/exercism/configlet) version will add support for doing this syncing automatically.
If the Practice Exercise was _not_ based on a problems-specifications exercise, we've used the blurb from its …
> 🤖 Add blurb to .meta/config.json files

- exercises/concept/booleans/.meta/config.json
The authors and contributors of exercises are stored in an array of objects in the exercises' `.meta/config.json` files.
Each author/contributor used to have two properties: their GitHub username _and_ their Exercism username.
As we're only using the GitHub username, we're flattening the `authors` and `contributors` array to an array of strings representing the GitHub usernames.
We will update `configlet` to validate the new structure, so you might be seeing build failures once we've implemented this change. 
See https://github.com/exercism/docs/pull/90/files
We will automatically merge this PR immediately to be able to submit a different PR in which we'll add the authors/contributors for practice exercises.
https://github.com/exercism/v3-launch/issues/26
> 🤖 Flatten authors and contributors in .meta/config.json files

- concepts/booleans/about.md
- concepts/booleans/introduction.md
- docs/ABOUT.md
- docs/INSTALLATION.md
- docs/LEARNING.md
- docs/RESOURCES.md
- docs/TESTS.md
- exercises/concept/booleans/.docs/hints.md
- exercises/concept/booleans/.docs/instructions.md
- exercises/concept/booleans/.docs/introduction.md
- reference/purescript-concepts/guides/Differences-from-Haskell.md
- reference/purescript-concepts/guides/Error-Suggestions.md
- reference/purescript-concepts/guides/FFI.md
We've defined a [specification for Markdown files](https://github.com/exercism/docs/blob/main/contributing/standards/markdown.md) to be applied Exercism-wide. This standard includes, amongst others, the following two rules:
- All files must start start with a level-1 heading (`# Some heading text`)
- No heading may decend a level greater than one below the previous (e.g. `## may only be followed by ###, not ####`)
This PR applies the above two rules to the Markdown documents in this repo. 
https://github.com/exercism/v3-launch/issues/17
> [v3] Update Markdown files to latest spec

- config.json
- Enable test-runner
- Set average run time for test runner to 3 seconds. The run-time is
based on running all exercise solutions on a 2015 MacBook Pro. Some
stats (in seconds):
- minimum: 2.042
- maximum: 6.005
- median: 2.280
- average: 2.436
> Enable PureScript test-runner

- config.json
In Exercism v3, tracks can be annotated with tags. This allows searching
for tracks with a certain tag combination, making it easy for students
to find an interesting track to join.
Resolves: https://github.com/exercism/purescript/issues/160
> [v3] Add tags

- exercises/concept/booleans/.docs/instructions.md
The `## Tasks` heading should not be in `instructions.md` files.
> Remove Tasks heading from instructions.md

- exercises/practice/accumulate/.meta/tests.toml
- exercises/practice/acronym/.meta/tests.toml
- exercises/practice/all-your-base/.meta/tests.toml
- exercises/practice/allergies/.meta/tests.toml
- exercises/practice/atbash-cipher/.meta/tests.toml
- exercises/practice/binary-search/.meta/tests.toml
- exercises/practice/bob/.meta/tests.toml
- exercises/practice/collatz-conjecture/.meta/tests.toml
- exercises/practice/crypto-square/.meta/tests.toml
- exercises/practice/diamond/.meta/tests.toml
- exercises/practice/difference-of-squares/.meta/tests.toml
- exercises/practice/etl/.meta/tests.toml
- exercises/practice/hamming/.meta/tests.toml
- exercises/practice/hello-world/.meta/tests.toml
- exercises/practice/isogram/.meta/tests.toml
- exercises/practice/largest-series-product/.meta/tests.toml
- exercises/practice/leap/.meta/tests.toml
- exercises/practice/matching-brackets/.meta/tests.toml
- exercises/practice/meetup/.meta/tests.toml
- exercises/practice/pangram/.meta/tests.toml
- exercises/practice/pascals-triangle/.meta/tests.toml
- exercises/practice/phone-number/.meta/tests.toml
- exercises/practice/raindrops/.meta/tests.toml
- exercises/practice/rna-transcription/.meta/tests.toml
- exercises/practice/scrabble-score/.meta/tests.toml
- exercises/practice/sum-of-multiples/.meta/tests.toml
- exercises/practice/triangle/.meta/tests.toml
- exercises/practice/word-count/.meta/tests.toml
We're in the process of re-opening the [Problem Specifications repo](https://github.com/exercism/problem-specifications), as discussed in [this issue](https://github.com/exercism/problem-specifications/issues/1674).
This PR adds `.meta/tests.toml` files for all exercises for which canonical data is defined in the Problem Specifications repo.
We'll now discuss _why_ we're making this change.
While most of the changes to the Problem Specifications repo are specific to that repo, there is one track-specific change:
> If a track implements an exercise for which test data exists, the exercise _must_ contain a `.meta/tests.toml` file.
The goal of the `tests.toml` file is to keep track of which tests are implemented by the exercise.
Tests in this file are identified by their UUID and each test …
> Bringing your track in line with the latest changes to Problem Specifications

- exercises/concept/booleans/spago.dhall
- exercises/concept/booleans/test/Main.purs
Prefer using the `test-unit` library over `spec`. The majority of tests
are written using `test-unit` already and we'd like to standardize on
it. The "booleans" concept exercise is the only one using spec.
Addresses #188
> Port unit tests from spec to test-unit

- exercises/practice/hello-world/examples/src/HelloWorld.purs
- exercises/practice/hello-world/src/HelloWorld.purs
- exercises/practice/hello-world/test/Main.purs
Simplify the `hello-world` exercise's stub. The goal of this is to make things easier for students to get started and to introduce as little syntax as possible.
See https://github.com/exercism/v3-launch/issues/46
> 🤖 Simplify `hello-world` stub

- exercises/concept/booleans/.meta/config.json
- exercises/practice/accumulate/.meta/config.json
- exercises/practice/acronym/.meta/config.json
- exercises/practice/all-your-base/.meta/config.json
- exercises/practice/allergies/.meta/config.json
- exercises/practice/atbash-cipher/.meta/config.json
- exercises/practice/binary-search/.meta/config.json
- exercises/practice/bob/.meta/config.json
- exercises/practice/collatz-conjecture/.meta/config.json
- exercises/practice/crypto-square/.meta/config.json
- exercises/practice/diamond/.meta/config.json
- exercises/practice/difference-of-squares/.meta/config.json
- exercises/practice/etl/.meta/config.json
- exercises/practice/hamming/.meta/config.json
- exercises/practice/hello-world/.meta/config.json
- exercises/practice/isogram/.meta/config.json
- exercises/practice/largest-series-product/.meta/config.json
- exercises/practice/leap/.meta/config.json
- exercises/practice/matching-brackets/.meta/config.json
- exercises/practice/meetup/.meta/config.json
- exercises/practice/pangram/.meta/config.json
- exercises/practice/pascals-triangle/.meta/config.json
- exercises/practice/phone-number/.meta/config.json
- exercises/practice/raindrops/.meta/config.json
- exercises/practice/rna-transcription/.meta/config.json
- exercises/practice/scrabble-score/.meta/config.json
- exercises/practice/sum-of-multiples/.meta/config.json
- exercises/practice/triangle/.meta/config.json
- exercises/practice/word-count/.meta/config.json
In a previous PR, the `files.invalidator` field was added to the track's `config.json`, but not to the actual exercises.
That means that no invalidator files were actually used.
This PR fixes that.
> Add invalidator files to exercises

- .github/workflows/ci.yml
These version comments are not updated by dependabot and thus will become stale. The SHA alone is sufficient and thus we'll remove the version comment. @ErikSchierboom
> Remove action version comments

- exercises/practice/largest-series-product/.docs/instructions.md
- exercises/practice/largest-series-product/.docs/introduction.md
- exercises/practice/largest-series-product/.meta/tests.toml
- exercises/practice/largest-series-product/test/Main.purs
The largest-series-product exercise has been overhauled as part of a project to make practice exercises more consistent and friendly.
For more context, please see the discussion in the forum, as well as the pull request that updated the exercise in the problem-specifications repository:
- https://forum.exercism.org/t/new-project-making-practice-exercises-more-consistent-and-human-across-exercism/3943
- https://github.com/exercism/problem-specifications/pull/2246 
Note that we have deprecated and removed two test cases that deal with the multiplicative identity (also referred to as an empty product). By doing this we were able to avoid talking about this at all, which makes this exercise much more approachable.
----
If you approve this pull request, I will eventually merge it. However, if …
> Sync largest-series-product docs with problem-specifications
