- .gitignore
- config.json
- exercises/hello-world/bower.json
- exercises/hello-world/examples/src/HelloWorld.purs
- exercises/hello-world/src/HelloWorld.purs
- exercises/hello-world/test/Main.purs
Hello! I wanted to learn purescript, but alas, there is no exercise course. I figure I may as well try and build one while learning.
> Add hello-world exercise

- .travis.yml
> Save bower cache on CI

- config.json
- exercises/word-count/bower.json
- exercises/word-count/examples/src/WordCount.purs
- exercises/word-count/src/WordCount.purs
- exercises/word-count/test/Main.purs
I'm new to both Exercism and PureScript - big thanks to all of you for investing so much into these projects!
If you have a moment, please let me know if this looks good and if anything needs or is worth changing, especially whether:
* The code is idiomatic, including any stylistic comments (formatting, verbosity, hard to read, too basic, etc.)
* There are other approaches I should have taken or considered (different types, functions, algorithms, etc.)
* Using non-Prelude packages (`purescript-maps` in this case) is OK
* The pull request is good
Cheers!
> Add Word Count exercise

- config.json
- exercises/meetup/bower.json
- exercises/meetup/examples/src/Meetup.purs
- exercises/meetup/src/Meetup.purs
- exercises/meetup/test/Main.purs
Please let me know if there's something worth changing to make the code clearer.
> Added Meetup exercise

- config.json
- exercises/atbash-cipher/bower.json
- exercises/atbash-cipher/examples/src/AtbashCipher.purs
- exercises/atbash-cipher/src/AtbashCipher.purs
- exercises/atbash-cipher/test/Main.purs
Let me know if something can be improved.
> Added Atbash cipher exercise

- config.json
- exercises/bracket-push/bower.json
- exercises/bracket-push/examples/src/BracketPush.purs
- exercises/bracket-push/src/BracketPush.purs
- exercises/bracket-push/test/Main.purs
Let me know if I can improve anything.
> Added Bracket push exercise

- config.json
- exercises/allergies/bower.json
- exercises/allergies/examples/src/Allergies.purs
- exercises/allergies/src/Allergies.purs
- exercises/allergies/test/Main.purs
Let me know if I can make any improvements.
> Added Allergies exercise

- config.json
- exercises/all-your-base/bower.json
- exercises/all-your-base/examples/src/AllYourBase.purs
- exercises/all-your-base/src/AllYourBase.purs
- exercises/all-your-base/test/Main.purs
> Added All Your Base exercise

- config.json
- exercises/binary-search/bower.json
- exercises/binary-search/examples/src/BinarySearch.purs
- exercises/binary-search/src/BinarySearch.purs
- exercises/binary-search/test/Main.purs
Let me know if I can improve something.
> Added Binary Search exercise

- config.json
- exercises/difference-of-squares/bower.json
- exercises/difference-of-squares/examples/src/DifferenceOfSquares.purs
- exercises/difference-of-squares/src/DifferenceOfSquares.purs
- exercises/difference-of-squares/test/Main.purs
> Added Difference of Squares exercise

- .travis.yml
- bin/test-one.sh
- exercises/accumulate/bower.json
- exercises/acronym/bower.json
- exercises/all-your-base/bower.json
- exercises/allergies/bower.json
- exercises/atbash-cipher/bower.json
- exercises/binary-search/bower.json
- exercises/bob/bower.json
- exercises/bracket-push/bower.json
- exercises/difference-of-squares/bower.json
- exercises/hello-world/bower.json
- exercises/leap/bower.json
- exercises/meetup/bower.json
- exercises/pangram/bower.json
- exercises/raindrops/bower.json
- exercises/scrabble-score/bower.json
- exercises/triangle/bower.json
- exercises/word-count/bower.json
> Use Purescript v0.11.1

- config.json
- exercises/accumulate/bower.json
- exercises/diamond/bower.json
- exercises/diamond/examples/src/Diamond.purs
- exercises/diamond/src/Diamond.purs
- exercises/diamond/test/Main.purs
> Added Diamond exercise

- config.json
- exercises/crypto-square/bower.json
- exercises/crypto-square/examples/src/CryptoSquare.purs
- exercises/crypto-square/src/CryptoSquare.purs
- exercises/crypto-square/test/Main.purs
> Added Crypto square exercise

- config.json
- exercises/isogram/bower.json
- exercises/isogram/examples/src/Isogram.purs
- exercises/isogram/src/Isogram.purs
- exercises/isogram/test/Main.purs
> Added Isogram exercise

- config.json
- exercises/etl/bower.json
- exercises/etl/examples/src/Etl.purs
- exercises/etl/src/Etl.purs
- exercises/etl/test/Main.purs
> Added ETL exercise

- config.json
- exercises/pascals-triangle/bower.json
- exercises/pascals-triangle/examples/src/PascalsTriangle.purs
- exercises/pascals-triangle/src/PascalsTriangle.purs
- exercises/pascals-triangle/test/Main.purs
Let me know if I can improve something.
> Added Pascals triangle exercise

- docs/ABOUT.md
Adapted from the Haskell ABOUT.md
> Add standard compliant ABOUT.md

- config.json
Closes #1 
@kytrinyx If I understand the comments on #1, nothing else is blocking us, correct?
> Set active flag to true

- exercises/hello-world/README.md
As someone familiar with the PS ecosystem I knew how to get this up and running, but it would be pretty daunting for a brand new user.
> Add a "Tips" section to the Readme

- .travis.yml
See https://github.com/exercism/configlet/issues/80 for more details.
Also fixes #78 that was recently opened in this repo.
> Add track ID to configlet

- .travis.yml
- bin/test.sh
This made a fair difference for my project on CircleCI. Let's see if it helps on travis.
> Limit number of cores used by purs on CI

- config.json
Closes #101. I figured copying the description from [the website](http://www.purescript.org/) would be a good place to start.
> Add track introduction

- config.json
Changes the difficulty of pascals-triangle exercise from 3 to 4
> Change pascals-triangle difficulty from 3 to 4

- exercises/phone-number/bower.json
- exercises/phone-number/examples/src/PhoneNumber.purs
- exercises/phone-number/test/Main.purs
Uses maybe so we return `Nothing` instead of `"None"`
> Make the phone-number exercise use maybe

- exercises/concept/booleans/.meta/config.json
- exercises/practice/accumulate/.meta/config.json
- exercises/practice/acronym/.meta/config.json
- exercises/practice/all-your-base/.meta/config.json
- exercises/practice/allergies/.meta/config.json
- exercises/practice/atbash-cipher/.meta/config.json
- exercises/practice/binary-search/.meta/config.json
- exercises/practice/bob/.meta/config.json
- exercises/practice/bracket-push/.meta/config.json
- exercises/practice/collatz-conjecture/.meta/config.json
- exercises/practice/crypto-square/.meta/config.json
- exercises/practice/diamond/.meta/config.json
- exercises/practice/difference-of-squares/.meta/config.json
- exercises/practice/etl/.meta/config.json
- exercises/practice/hamming/.meta/config.json
- exercises/practice/hello-world/.meta/config.json
- exercises/practice/isogram/.meta/config.json
- exercises/practice/largest-series-product/.meta/config.json
- exercises/practice/leap/.meta/config.json
- exercises/practice/meetup/.meta/config.json
- exercises/practice/pangram/.meta/config.json
- exercises/practice/pascals-triangle/.meta/config.json
- exercises/practice/phone-number/.meta/config.json
- exercises/practice/raindrops/.meta/config.json
- exercises/practice/rna-transcription/.meta/config.json
- exercises/practice/scrabble-score/.meta/config.json
- exercises/practice/sum-of-multiples/.meta/config.json
- exercises/practice/triangle/.meta/config.json
- exercises/practice/word-count/.meta/config.json
To help tracks define the files in the exercise's `.meta/config.json` file, we've added support for defining these file patterns in the track's `config.json` file. See [this PR](https://github.com/exercism/docs/pull/58).
This PR updates the file paths defined in the `files` property of each exercise's `.meta/config.json` file according to the file patterns defined in the track's `config.json` file.
We only update a file path in the `.meta/config.json` file if:
- The file path pattern is a non-empty array in the `config.json` file
- The file path pattern is either not set or an empty array in the `.meta/config.json` file
This means that exercises that had already defined files in the `.meta/config.json` won't be touched in this PR.
Note that this PR is just an easy way for tracks to …
> 🤖 Sync exercise files keys based on file path patterns

- README.md
- exercises/practice/accumulate/src/Accumulate.purs
- exercises/practice/acronym/src/Acronym.purs
- exercises/practice/all-your-base/src/AllYourBase.purs
- exercises/practice/allergies/src/Allergies.purs
- exercises/practice/atbash-cipher/src/AtbashCipher.purs
- exercises/practice/binary-search/src/BinarySearch.purs
- exercises/practice/bob/src/Bob.purs
- exercises/practice/collatz-conjecture/src/CollatzConjecture.purs
- exercises/practice/crypto-square/src/CryptoSquare.purs
- exercises/practice/diamond/src/Diamond.purs
- exercises/practice/difference-of-squares/src/DifferenceOfSquares.purs
- exercises/practice/etl/src/Etl.purs
- exercises/practice/hamming/src/Hamming.purs
- exercises/practice/isogram/src/Isogram.purs
- exercises/practice/largest-series-product/src/LargestSeriesProduct.purs
- exercises/practice/leap/src/Leap.purs
- exercises/practice/matching-brackets/src/MatchingBrackets.purs
- exercises/practice/meetup/src/Meetup.purs
- exercises/practice/pangram/src/Pangram.purs
- exercises/practice/pascals-triangle/src/PascalsTriangle.purs
- exercises/practice/phone-number/src/PhoneNumber.purs
- exercises/practice/raindrops/src/Raindrops.purs
- exercises/practice/rna-transcription/src/RnaTranscription.purs
- exercises/practice/scrabble-score/src/ScrabbleScore.purs
- exercises/practice/sum-of-multiples/src/SumOfMultiples.purs
- exercises/practice/triangle/src/Triangle.purs
- exercises/practice/word-count/src/WordCount.purs
> Add signatures to all stub files

- .github/workflows/ci.yml
See: https://exercism.org/docs/building/github/gha-best-practices#h-pin-actions-to-shas
> GitHub: Pin Actions to SHAs

- config.json
- exercises/practice/spiral-matrix/.docs/instructions.md
- exercises/practice/spiral-matrix/.docs/introduction.md
- exercises/practice/spiral-matrix/.meta/config.json
- exercises/practice/spiral-matrix/.meta/tests.toml
- exercises/practice/spiral-matrix/.solution.dhall
- exercises/practice/spiral-matrix/examples/src/SpiralMatrix.purs
- exercises/practice/spiral-matrix/packages.dhall
- exercises/practice/spiral-matrix/spago.dhall
- exercises/practice/spiral-matrix/src/SpiralMatrix.purs
- exercises/practice/spiral-matrix/test/Main.purs
Implemented Spiral Matrix for #48in24
> spiral matrix: added exercise.

- config.json
- exercises/practice/knapsack/.docs/instructions.md
- exercises/practice/knapsack/.docs/introduction.md
- exercises/practice/knapsack/.meta/config.json
- exercises/practice/knapsack/.meta/tests.toml
- exercises/practice/knapsack/.solution.dhall
- exercises/practice/knapsack/examples/src/Knapsack.purs
- exercises/practice/knapsack/packages.dhall
- exercises/practice/knapsack/spago.dhall
- exercises/practice/knapsack/src/Knapsack.purs
- exercises/practice/knapsack/test/Main.purs
This is one of the [48in24 exercises](https://forum.exercism.org/t/48in24-exercise-08-13-knapsack/12054).
> Add Knapsack exercise

- exercises/concept/booleans/.docs/instructions.md
See https://github.com/exercism/exercism/issues/6005
Co-authored-by: Colin Caine <cmcaine@gmail.com>
> annalyn: Clarify description

- exercises/concept/annalyns-infiltration/.meta/config.json
Closes #171. Blurb is adapted from the JavaScript track.
> Update Annalyn blurb

- exercises/practice/spiral-matrix/test/Main.purs
Corrected the test inputs so test failure messages correctly show the actual and expected outputs
Forum discussion http://forum.exercism.org/t/spiral-matrix-tests-have-expected-and-actual-results-swapped/17474
> correct spiral matrix test inputs closes #315
